# Generated by Django 5.0.3 on 2024-12-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_customuser_image'),
        ('Api', '0004_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
    ]
