const Data = [
    {
        id: '1',
        author: 'Olawoyin',
        name: 'SWEET CHILLI CHICKEN',
        category: "Today's",
        image: '../images/sweet-chilli-chicken4177.png',
        description: 'Sweet Chilli sauce, chicken',
        price: "200",
        
    },
    {
        id: '2',
        author: 'Olawoyin',
        name: 'CHICKEN SUPREME',
        category: "Today's",
        image: '../images/chicken-supreme3419.png',
        description: 'Pizza sauce, Chicken, veggie mix',
        price: "120",
        
    },
    {
        id: '3',
        author: 'Olawoyin',
        name: "MAGHERITA",
        category: "Today's",
        image: '../images/margherita4053.png',
        description: 'Pizza sauce and Mozarella',
        price: "220",
        discount: "40",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '4',
        author: 'Olawoyin',
        name: "DOUBLE CHEESE",
        image: '../images/double-cheese2354.png',
        category: "Today's",
        description: 'Pizza sauce and Mozarella',
        price: "130",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '5',
        author: 'Olawoyin',
        name: "HUT CHILLI VEG",
        category: "Today's",
        image: '../images/hut-chilli-veg2664.png',
        description: 'BBQ sauce,Veggie mix, Pepperdew, black olives',
        price: "110",
        
    },
    {
        id: '6',
        author: 'Gbolahan',
        name: "PEPPER VEG",
        category: "",
        image: '../images/peppe--veg7935.png',
        description: 'Peri Peri Sauce, veggie mix, Jalapenos, Pepperdew',
        price: "300",
        
    },
    {
        id: '7',
        author: 'Gbolahan',
        name: "BBQ CHICKEN AND SUYA",
        category: "",
        image: '../images/bbq-chicken-and-suya9790.png',
        description: 'BBQ Sauce, Red Onions, Chicken suya, Green Pepper',
        price: "300",
        discount: "20",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '8',
        author: 'Gbolahan',
        name: "CHICKEN SAUSAGE",
        category: "Men's Clothing",
        image: '../images/chicken-sausage8239.png',
        description: 'Chicken Sausage',
        price: "230",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '9',
        author: 'Gbolahan',
        name: "HUT CHILLI CHICKEN ",
        category: "Men's Clothing",
        image: '../images/hut-chilli-chicken5202.png',
        description: 'Sweet Chilli Sauce, Chicken, Pepperdew, Red Onions, Green Pepper, Sweet Corn',
        price: "220",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '10',
        author: 'Gbolahan',
        name: "PEPPERONI",
        category: "Men's Clothing",
        image: '../images/pepperoni3450.png',
        description: 'Pepperoni and Mozarella',
        price: "110",
        discount: "20",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '11',
        author: 'Gbolahan',
        name: "SUPER SUPREME",
        category: "Men's Clothing",
        image: '../images/super-supreme3619.png',
        description: 'Pizza Sauce, Pepperoni, Sliced Macon , Beef, Diced Macon, Veggie mix, Olives, Macon',
        price: "100",
        discount: "40",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '12',
        author: 'Gbolahan',
        name: "TRIPLE MEAT SUYA",
        category: "Men's Clothing",
        image: '../images/triple-meat-suya2728.png',
        description: 'Pepperoni, Suya Beef, Sliced Macon',
        price: "90",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '13',
        author: 'Gbolahan',
        name: "HUT CHILLI MEAT",
        category: "Men's Clothing",
        image: '../images/hut-chilli-meat4151.png',
        description: 'Beef, BBQ Sauce, Red Onions, Green Pepper, Pepperdew',
        price: "",
        discount: "20",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '14',
        author: 'Gbolahan',
        name: "BBQ MEAT LOVERS",
        category: "Men's Clothing",
        image: '../images/bbq-meat-lovers4957.png',
        description: 'BBQ Sauce, Pepperoni, Beef, Slice Macon and Diced Macon',
        price: "99",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '16',
        author: 'Gbolahan',
        name: "BBQ CHICKEN AND MACON",
        category: "Men's Clothing",
        image: '../images/bbq-chicken-and-macon.png',
        description: 'BBQ sauce, Chicken and Diced Macon',
        price: "78",
        discount: "20",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '17',
        author: 'Gbolahan',
        name: "TANDORI CHICKEN",
        category: "Men's Clothing",
        image: '../images/tandoori-chicken2551.png',
        description: 'Tandori chicken.',
        price: "100",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '18',
        author: 'Gbolahan',
        name: "SHAWAMA CHICKEN",
        category: "Men",
        image: '../images/shawarma-chicken2468.png',
        description: 'shawama chicken',
        price: "100",
        discount: "20",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
   
   
   
]

export default Data