# Generated by Django 5.1.4 on 2024-12-28 06:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description_type', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=200)),
            ],
        ),
    ]
