# Generated by Django 5.1.4 on 2025-01-13 15:09

import pizza.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.UUIDField(blank=True, default=pizza.models.generate_uuid, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description_type', models.CharField(choices=[('Starters', 'Starters'), ('Classic', 'Classic'), ('Vegetarian', 'Vegetarian'), ('Meat-Lover’s', 'Meat-Lover’s')], default='Picked-up', max_length=30, null=True)),
                ('ingredients', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pizza/images/')),
            ],
        ),
    ]
