# Generated by Django 5.0.3 on 2025-01-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='description_type',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Classic', 'Classic'), ('Vegetarian', 'Vegetarian'), ('Meat-Lover’s', 'Meat-Lover’s')], default='Picked-up', max_length=30, null=True),
        ),
    ]
